
export const constants = {
    FETCH_TODO_LIST: 'FETCH_TODO_LIST',
    FETCH_TODO_LIST_SUCCESS: 'FETCH_TODO_LIST_SUCCESS',
    FETCH_TODO_LIST_FAILURE: 'FETCH_TODO_LIST_FAILURE',
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    EDIT_TODO: "EDIT_TODO",
    TOGGLE_TODO: "TOGGLE_TODO"
}